[WIP] feat: support windows vpcip
AliyunContainerService/terway pull request #248
Opened 2021-07-29 07:09 UTC by thxCode

2022-02-14 07:39 UTC, l1b0k requested changes

2022-02-14 07:39 UTC, l1b0k commented on pkg/windows/iface/iface.go
> +	Dual AddressFamily = ""
Default 为空，是否有歧义？

2022-02-14 07:39 UTC, l1b0k commented on pkg/windows/apis/network_bridge.go
> +	return (ipv4Net.IP + 2).ToIP()
will the result still in the subnet range?

2022-02-14 07:39 UTC, l1b0k commented on pkg/windows/apis/network_bridge.go
> +			if _, err := deleteHCNEndpoint(ep, ""); err != nil {
重定义是否有问题？ L167

2022-02-15 02:07 UTC, thxCode commented on pkg/windows/iface/iface.go
> +	Dual AddressFamily = ""
Dual means both IPv4 and IPv6, any Powershell command which supports `-AddressFamily` can accept an empty list(`None` value) and treat it as [IPv4, IPv6]. The following doc explains more details: https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-netipaddress?view=windowsserver2022-ps.

![image](https://user-images.githubusercontent.com/3394724/153978862-74ba6287-08d7-4931-8a2d-d2ddcf814d35.png)

2022-02-15 02:30 UTC, thxCode commented on pkg/windows/apis/network_bridge.go
> +	return (ipv4Net.IP + 2).ToIP()
Yes or not, if the range is small enough, here will bit us. In a reasonable case, the default gateway of Pod HNSEndpoint is used for avoiding stuck in ARP response during outbound connectivity. Other CNI plugins give the same workaround in here, [win-bridge](https://github.com/containernetworking/plugins/blob/76307bf0f6929b39986f1c6f5e4b6abdb82b8815/plugins/main/windows/win-bridge/win-bridge_windows.go#L81-L82), [sdnbridge](https://github.com/microsoft/windows-container-networking/blob/a150f21845c673422b8f70967e16e998fb052ab8/common/core/network.go#L353-L356).

2022-02-15 02:37 UTC, thxCode commented on pkg/windows/apis/network_bridge.go
> +			if _, err := deleteHCNEndpoint(ep, ""); err != nil {
Corrupted validation is a fuse, that only be `true` if the HNSNetwork type is changed or the target IP address is changed but the name still be the same. So we can just clean the stale endpoint and create again. On the other hand, if an HNSNetwork has been cleaned, those HNSEndpoints which attaching will clean as well.

2022-02-15 08:07 UTC, l1b0k approved these changes

2022-03-01 02:15 UTC, merged