fix: Teardown may cause resource leak
AliyunContainerService/terway pull request #294
Opened 2021-12-13 07:01 UTC by l1b0k

In containerd environment , containers cannot be destroyed when cni return err.
This PR can alleviate this situation.

2021-12-17 06:57 UTC, BSWANG requested changes

2021-12-17 06:57 UTC, BSWANG commented on plugin/terway/cni.go
>  	case rpc.IPType_TypeVPCENI:
建议下面加一下break，避免引起误解

2021-12-17 06:57 UTC, BSWANG commented on plugin/terway/cni.go
> +	err = driver.GenericTearDown(cniNetns)
cmdAdd的defer中是否也需要改成GenericTearDown?

2021-12-17 06:57 UTC, BSWANG commented on plugin/terway/cni.go
> +	err = driver.GenericTearDown(cniNetns)
GenericTearDown是否需要加cni的锁，避免中间状态中被执行teardown?

2021-12-17 06:57 UTC, BSWANG commented on plugin/driver/utils.go
> +			err = RuleDel(&r)
如果这里rule删除出错了，会导致之前已经删除的 ipNets的 to 方向的路由泄漏，先保存下来一起删除

2021-12-20 04:39 UTC, l1b0k commented on plugin/driver/utils.go
> +			err = RuleDel(&r)
done

2021-12-20 04:39 UTC, l1b0k commented on plugin/terway/cni.go
> +	err = driver.GenericTearDown(cniNetns)
done

2021-12-20 04:39 UTC, l1b0k commented on plugin/terway/cni.go
> +	err = driver.GenericTearDown(cniNetns)
done

2021-12-20 06:31 UTC, merged