feat: create eni with specificed resourceGroupID
AliyunContainerService/terway pull request #381
Opened 2022-06-23 12:21 UTC by zyliu404

2022-10-11 11:36 UTC, l1b0k requested changes

2022-10-11 11:36 UTC, l1b0k commented on pkg/controller/pool/eni_mgr.go
> +		if resourceGroupID != "" {
这个为什么需要

2022-10-11 11:36 UTC, l1b0k commented on pkg/aliyun/client/types.go
> +	ResourceGroupId    string             `json:"resource_group_id,omitempty"`
ID

2022-10-13 06:35 UTC, zyliu404 commented on pkg/controller/pool/eni_mgr.go
> +		if resourceGroupID != "" {
ModifyNetworkInterfaceAttribute 不支持修改资源组

2022-10-14 01:57 UTC, l1b0k approved these changes

2022-10-14 01:58 UTC, merged