daemon: init cni conf after terway stated
AliyunContainerService/terway pull request #606
Opened 2024-04-17 12:32 UTC by l1b0k

2024-04-17 13:32 UTC, BSWANG requested changes

2024-04-17 13:32 UTC, BSWANG commented on daemon/server.go
> +	src, err := os.Open(filepath.Join(tmpCNIConfigPath, cinConfFile))
should omit  NotExist error?

2024-04-18 01:16 UTC, l1b0k commented on daemon/server.go
> +	src, err := os.Open(filepath.Join(tmpCNIConfigPath, cinConfFile))
CNI file must be present.

2024-04-18 01:31 UTC, BSWANG approved these changes

2024-04-18 01:31 UTC, merged