feat(eni): add selection policy
AliyunContainerService/terway pull request #636
Opened 2024-05-28 03:37 UTC by exherb

2024-05-29 02:39 UTC, l1b0k requested changes

2024-05-29 02:39 UTC, l1b0k commented on daemon/config.go
> +	eniSelectionPolicy := types.EniSelectionPolicyLeast
定义可能引起歧义，eni选择策略的"most"意味着优先选择IP数量多的eni，而"least"则指选择IP少的eni。
考虑两种改法，我觉得第一种可能好点
- "most"调度策略，表示优先考虑IP地址多的eni，"least"策略则倾向于IP地址少的eni。
- "most"创建策略，意味着尽量创建更多的eni，而"least"策略则是尽量创建少的eni。

2024-05-29 02:39 UTC, l1b0k commented on pkg/eni/manager.go
> +	switch m.selectionPolicy {
https://github.com/AliyunContainerService/terway/blob/879ee02d111566d0a72fe5b7657c77861b58bb17/pkg/eni/manager.go#L269

也需要排序

2024-05-30 07:06 UTC, exherb commented on daemon/config.go
> +	eniSelectionPolicy := types.EniSelectionPolicyLeast
改成第一种了, 并且语义改成了 most_ips (默认值) least_ips (可选)

2024-06-05 01:33 UTC, l1b0k commented
@exherb go test failed

2024-06-15 01:13 UTC, exherb commented
> @exherb go test failed

I will fix it

2024-06-17 06:42 UTC, exherb commented
@l1b0k 测试应该能过了, 不过不知道为啥测试没跑

2024-06-20 06:30 UTC, l1b0k commented on types/daemon/config.go
> +	EniSelectionPolicy     string              `yaml:"eni_selection_policy" json:"eni_selection_policy" mod:"default=least"`
should this be `least_ips` ?

2024-07-03 09:30 UTC, exherb commented on types/daemon/config.go
> +	EniSelectionPolicy     string              `yaml:"eni_selection_policy" json:"eni_selection_policy" mod:"default=least"`
sorry fixed

2024-07-03 09:30 UTC, exherb commented
@l1b0k please review again, sorry for the delay.

2024-07-04 07:52 UTC, l1b0k approved these changes

2024-07-04 08:00 UTC, merged

2024-07-04 08:00 UTC, l1b0k commented
@exherb Thanks for your contribution.